In [ ]:
# 一、Pytorch基本操作考察（平台课+专业课）

In [ ]:
# 1.
# 使用 𝐓𝐞𝐧𝐬𝐨𝐫 初始化一个 𝟏 × 𝟑 的矩阵 𝑴 和一个 𝟐 × 𝟏 的矩阵 𝑵，对两矩阵进行减法操作（要求实现三种不同的形式），给出结果并分析三种方式的不同（如果出现报错，分析报错的原因），同时需要指出在计算过程中发生了什么

In [2]:
import torch

In [4]:
M = torch.tensor([[1], [2], [3]])
N = torch.tensor([4, 5])
Q = M - N
print(Q)

tensor([[-3, -4],
        [-2, -3],
        [-1, -2]])


In [9]:
M_2 = torch.rand_like(M, dtype=torch.float)
N_2 = torch.rand_like(N, dtype=torch.float)
Q_2 = M - N
print(Q_2)

tensor([[-3, -4],
        [-2, -3],
        [-1, -2]])


In [10]:
M_3 = torch.ones(1, 3)
N_3 = torch.ones(2, 1)
Q_3 = M_3 - N_3
print(Q_3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# 2.
# ① 利用 𝐓𝐞𝐧𝐬𝐨𝐫 创建两个大小分别 𝟑 × 𝟐 和 𝟒 × 𝟐 的随机数矩阵 𝑷 和 𝑸 ，要求服从均值为0，标准差0.01为的正态分布

In [11]:
P = torch.normal(0, 0.01, (3, 2))
Q = torch.normal(0, 0.01, (4, 2))
print(P)
print(Q)

tensor([[ 0.0015, -0.0076],
        [ 0.0172,  0.0250],
        [ 0.0125, -0.0004]])
tensor([[ 0.0008,  0.0104],
        [-0.0054, -0.0046],
        [-0.0199,  0.0153],
        [-0.0008, -0.0010]])


In [ ]:
# ② 对第二步得到的矩阵 𝑸 进行形状变换得到 𝑸 的转置 𝑸𝑻

In [12]:
QT = Q.T
print(QT)

tensor([[ 0.0008, -0.0054, -0.0199, -0.0008],
        [ 0.0104, -0.0046,  0.0153, -0.0010]])


In [ ]:
# ③ 对上述得到的矩阵 𝑷 和矩阵 𝑸𝑻 求矩阵相乘

In [14]:
PQT = torch.mm(P, QT)
print(PQT)

tensor([[-7.8270e-05,  2.7024e-05, -1.4622e-04,  6.4623e-06],
        [ 2.7337e-04, -2.0765e-04,  4.1129e-05, -3.8444e-05],
        [ 5.4841e-06, -6.5841e-05, -2.5488e-04, -9.4149e-06]])


In [ ]:
# 3.
# 给定公式 𝑦3 = 𝑦1 + 𝑦2 = 𝑥^2 + 𝑥^3，且 𝑥 = 1。利用学习所得到的Tensor的相关知识，求𝑦3对𝑥的梯度，即𝑑𝑦3/𝑑𝑥
# 要求在计算过程中，在计算 𝑥3 时中断梯度的追踪，观察结果并进行原因分析
# 提示, 可使用 with torch.no_grad()， 举例:
# with torch.no_grad():
# y = x * 5